"""
hack/reporting/skill_md.py
---------------------------
SkillMdGenerator — produces a compact SKILL.md for an AI agent to ingest.

The output is intentionally small: an agent should be able to load it into
context and know exactly how to interact with the audited service.
"""

from __future__ import annotations

from ..models.compliance import ServiceAuditReport, SoulboundCertificate


class SkillMdGenerator:
    """Render a ServiceAuditReport → SKILL.md text."""

    def render(
        self,
        report: ServiceAuditReport,
        certificate: SoulboundCertificate | None = None,
    ) -> str:
        req = report.request
        lines: list[str] = []

        lines.append(f"# {req.service_name} — x402 Skill")
        lines.append("")
        lines.append(
            f"> Compliance score **{report.overall_score:.0f}/100** "
            f"({report.grade}). "
            f"{'Certified soulbound' if certificate else 'Uncertified'}."
        )
        lines.append("")

        # ── Service metadata ──
        lines.append("## Service")
        lines.append(f"- **Type:** {req.service_type}")
        lines.append(f"- **Endpoint:** `{req.endpoint_url}`")
        if req.repo_url:
            lines.append(f"- **Source:** {req.repo_url}")
        lines.append("")

        # ── On-chain trust anchor ──
        if certificate:
            lines.append("## On-chain trust anchor")
            lines.append(f"- **NFT token:** `{certificate.token_id}` (serial #{certificate.serial_number})")
            lines.append(f"- **Mint transaction:** {certificate.hashscan_tx_url}")
            lines.append(f"- **Metadata SHA-256:** `{certificate.metadata_hash}`")
            if certificate.hcs_topic_id:
                lines.append(f"- **HCS topic:** `{certificate.hcs_topic_id}`")
            lines.append("")

        # ── Behavioural rules ──
        lines.append("## When calling this service — rules for AI agents")
        lines.append("")
        lines.append("Always:")
        lines.append("- Start with an unauthenticated request; expect **HTTP 402**.")
        lines.append("- Parse the challenge (`quote_id`, `amount`, `receiver`, `memo`, `expiry`).")
        lines.append("- Send HBAR to `receiver` on Hedera testnet with the exact memo.")
        lines.append("- Retry the original request with `X-Quote-Id` and `X-Payment-Token` headers.")
        lines.append("- Wait for **Mirror Node** confirmation before considering the payment settled.")
        lines.append("")
        lines.append("Never:")
        lines.append("- Reuse a `quote_id` — every request needs a fresh challenge.")
        lines.append("- Cache the response without also recording the `quote_id` it was paid with.")
        lines.append("- Sign transactions with the service operator's key — that is server-side.")
        lines.append("")

        # ── Findings the agent should be aware of ──
        failing = [f for s in report.sections for f in s.findings if f.status == "failed"]
        warnings = [f for s in report.sections for f in s.findings if f.status == "warning"]
        if failing or warnings:
            lines.append("## Known limitations of this service")
            for f in failing:
                lines.append(f"- **{f.title}** — {f.detail}")
            for f in warnings:
                lines.append(f"- {f.title} — {f.detail}")
            lines.append("")

        # ── Recommendations (context for the agent operator, not calling behaviour) ──
        if report.recommendations:
            lines.append("## Operator recommendations")
            for r in report.recommendations:
                lines.append(f"- {r}")
            lines.append("")

        lines.append("---")
        lines.append(
            f"Generated by the Hedera Agent Commerce Kit compliance engine · report `{report.report_id}`."
        )
        return "\n".join(lines) + "\n"
